### ISSUE TITLE
Replace the default "Game Over" browser alert with custom dialog window

### ISSUE THREAD

**Issue by matronator** [matronator/feed-the-flames#14]
When the game ends, it should show a custom in-game modal/dialog window instead of the default JavaScript `alert(...);` browser alert.

**Comment by rjdoughty** [comment]
i would like to give this a try

**Comment by matronator** [comment]
That'd be great, thanks! When you're done, just make a pull request referencing this issue. If you need help with anything, let me know :)

**Comment by c3ho** [comment]
Hi, is this issue fixed?

**Comment by anmol5varma** [comment]
Is this issue fixed?

**Comment by matronator** [comment]
#18
