### ISSUE TITLE
Turn pause icon to play icon and vice versa when clicked

### ISSUE THREAD

**Issue by tag6071** [matronator/feed-the-flames#5]
Currently, when the game is on and the player clicks the pause icon below the page to temporarily stop the game, the pause icon remains the same.

This can be improved to ensure the pause icon is changed to play icon and vice-versa whenever it is clicked for a good user experience.

**Comment by matronator** [comment]
Could be a good first issue for new contributors, thanks! I'm leaving this open for now, so if anyone wants to take this issue, you can use the [playButton.png](https://github.com/matronator/feed-the-flames/blob/master/img/playButton.png) I added to the img folder.

**Comment by hannesfant** [comment]
On this!
