### ISSUE TITLE
Update UI for Main Menu Scheme

### ISSUE THREAD

**Issue by reduncan** [matronator/feed-the-flames#8]
When looking at your main menu it is not very user friendly. I would like to add some styling and layout the style of the main menu to make it more readable and enjoyable to the eye.

**Comment by matronator** [comment]
Oh yeah, good idea! I totally forgot about the horrendous "menu" screen. Feel free to style it how you like and let me know if you'll need help with anything!

**Comment by reduncan** [comment]
Created PR for this issue. Let me know your thoughts!
